// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PsychotherapistApp.Data.Contexts;

namespace PsychotherapistApp.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20221216124505_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PsychotherapistApp.Data.Models.CalendarRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("time");

                    b.Property<int>("Frequency")
                        .HasColumnType("int");

                    b.Property<int>("PsychotherapistId")
                        .HasColumnType("int");

                    b.Property<int>("RoomNumber")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.HasIndex("PsychotherapistId");

                    b.ToTable("CalendarRecords");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Description1",
                            EndTime = new TimeSpan(0, 2, 30, 0, 0),
                            Frequency = 1,
                            PsychotherapistId = 1,
                            RoomNumber = 1,
                            StartTime = new TimeSpan(0, 2, 0, 0, 0)
                        },
                        new
                        {
                            Id = 2,
                            Description = "Description2",
                            EndTime = new TimeSpan(0, 2, 0, 0, 0),
                            Frequency = 0,
                            PsychotherapistId = 2,
                            RoomNumber = 1,
                            StartTime = new TimeSpan(0, 1, 0, 0, 0)
                        });
                });

            modelBuilder.Entity("PsychotherapistApp.Data.Models.Psychotherapist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Psychotherapists");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "bob.green@gmail.com",
                            Name = "Bob",
                            Surname = "Green"
                        },
                        new
                        {
                            Id = 2,
                            Email = "john.smith@gmail.com",
                            Name = "John",
                            Surname = " Smith"
                        });
                });

            modelBuilder.Entity("PsychotherapistApp.Data.Models.CalendarRecord", b =>
                {
                    b.HasOne("PsychotherapistApp.Data.Models.Psychotherapist", "Psychotherapist")
                        .WithMany("CalendarRecords")
                        .HasForeignKey("PsychotherapistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Psychotherapist");
                });

            modelBuilder.Entity("PsychotherapistApp.Data.Models.Psychotherapist", b =>
                {
                    b.Navigation("CalendarRecords");
                });
#pragma warning restore 612, 618
        }
    }
}
